%YAML:1.0

#common parameters
image_topic: "/pylon_camera_node/image_raw"
sensor_name: "pylon"

#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 1920
image_height: 1200
distortion_parameters:
   k1: -0.140744
   k2: -0.022508
   p1: 0.002406
   p2: -0.002769
   k3: 0
projection_parameters:
   fx: 2699.508250
   fy: 2694.726579
   cx: 924.581509
   cy: 681.996805

#feature traker paprameters
max_cnt: 1000          # max feature number in feature tracking
min_dist: 50            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#triangulation
max_dist: 1000
rep_err: 0.5


